# Generated by Django 4.2.3 on 2023-07-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_driver",
        ),
    ]
